name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - run: ls -l
      - name: download artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: generate.yml
          workflow_conclusion: success
          name: sarasa-nerd-font-ttc.zip
      - run: ls -l
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
